/***************************************************************************************
    CLIENT
        Restoration Hardware
            
    PURPOSE
	Test Coverage for CaseAssignment class
        
    ENTRY POINTS
         CaseAssignment              
    
    CHANGE LOG
        [[Version; Date; Author; Description]]
        v0.1; 2014/06/1; Carl Weiss/Forefront;
***************************************************************************************/
@isTest
private class caseAssignment_Test {
	
	@isTest(SeeAllData=true) static void test_method_one() 
	{
		
	}
	
	
}