/* This is a test class for CreateNewCaseLineController */
@isTest
private class CreateNewCaseLineController_Test {
/*
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        PrepareData.populateCustomSettings();
        //Creating a RH Order
        RH_Order__c rhOrder=new RH_Order__c();
        rhOrder.Name='ORDER 123';
        insert rhOrder;
        
        Case c=new Case();
        c.Original_Requested_Percentage__c=.95;
        c.Order_Number__c=rhOrder.Id;
        insert c;
        
        Case_Line_Items__c cli=new Case_Line_Items__c();
        cli.Case_Number__c=c.Id;
        insert cli;
        
        PageReference pr=new PageReference('/apex/CreateNewCaseLine');
        Test.setCurrentPage(pr);
        ApexPages.currentPage().getParameters().put('caseId', c.Id);
        ApexPages.currentPage().getParameters().put('orderId', rhOrder.Id);
        ApexPages.currentPage().getParameters().put('retURL', '/' + rhOrder.Id);
        ApexPages.currentPage().getParameters().put('retURL', '/' + rhOrder.Name);
        
        CreateNewCaseLineController cn=new CreateNewCaseLineController();
        cn.navigateToURL();
        
    }
*/
}